DROP TABLE IF EXISTS users, categories, location;
CREATE TABLE IF NOT EXISTS users (
    id                      BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255)                    NOT NULL,
    email                   VARCHAR(255)                    NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS categories (
    id                      BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255)                    NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS locations (
    id                      BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255)                    NOT NULL,
    description             VARCHAR(7000),
    latitud                 DOUBLE PRECISION                NOT NULL,
    longitude               DOUBLE PRECISION                NOT NULL
    );

CREATE TABLE IF NOT EXISTS events (
    id                      BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation              VARCHAR(2000)                   NOT NULL,
    category_id             BIGINT                          NOT NULL REFERENCES categories(id),
    description             VARCHAR(7000)                   NOT NULL,
    eventDate               TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
    location_id             BIGINT                          NOT NULL REFERENCES locations(id),
    is_paid                 BOOLEAN,
    participant_limit       INT,
    is_request_moderation   BOOLEAN,
    title                   VARCHAR(120)                   NOT NULL
    );