DROP TABLE IF EXISTS events, locations, categories, users;
CREATE TABLE IF NOT EXISTS users (
    id                      BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255)                    NOT NULL,
    email                   VARCHAR(255)                    NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS categories (
    id                      BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255)                    NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS locations (
    id                      BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255),
    description             VARCHAR(7000),
    latitude                DOUBLE PRECISION                NOT NULL,
    longitude               DOUBLE PRECISION                NOT NULL
    );

CREATE TABLE IF NOT EXISTS events (
    id                      BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation              VARCHAR(2000)                   NOT NULL,
    category_id             BIGINT                          NOT NULL REFERENCES categories(id),
    created_on              TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
    description             VARCHAR(7000)                   NOT NULL,
    event_date              TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
    initiator_id            BIGINT                          NOT NULL REFERENCES users(id),
    location_id             BIGINT                          NOT NULL REFERENCES locations(id),
    is_paid                 BOOLEAN                         NOT NULL,
    participant_limit       INT                             NOT NULL,
    published_on            TIMESTAMP WITHOUT TIME ZONE,
    is_request_moderation   BOOLEAN                         NOT NULL,
    state                   VARCHAR(20)                     NOT NULL,
    title                   VARCHAR(120)                    NOT NULL
    );